version: "3.9"

services:
  postgres:
    image: postgres:11-alpine
    container_name: keycloak_db
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  keycloak:
    image: ghcr.io/coduction/keycloak:arm
    container_name: keycloak
    restart: unless-stopped
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: ${KC_ADMIN_USER}
      KEYCLOAK_USER_PASSWORD: ${KC_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${DB_NAME}
      KC_DB_URL_PROPERTIES: '?'
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      KC_LOG_LEVEL: INFO
    ports:
      - "8100:8080"
    depends_on:
      - postgres

networks:
  default:
    name: net_keycloak
    driver: bridge
